### ISSUE TITLE
Update the version of Wolfram Engine for Windows

### ISSUE THREAD

**Issue by njpipeorgan** [WolframResearch/WL-FunctionCompile-CI-Template#2]
[The link](https://github.com/WolframResearch/WL-FunctionCompile-CI-Template/blob/3916b99477a8e988890585270c87b3cf345fd615/.github/workflows/compile-wl-functions.yml#L8) to the installation for Windows is hard coded to be 12.2 in the template. Is there any plan to update that to the newest version of the Engine?

**Comment by okofish** [comment]
It [looks like](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WolframResearch/WolframEngine) 12.2 is the latest version available from the location where the workflow downloads the installer (it piggybacks off the MSI installer prepared for use with the winget package manager).

I'm told that work is underway on releasing a 13.0 update for the winget package, so I'll leave this issue open until that happens.

CC @cc-wr
